--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: games; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.games (
    id bigint NOT NULL,
    cover_image_url character varying(255),
    description character varying(1000),
    developer character varying(255),
    genre character varying(255),
    price numeric(38,2),
    release_date date,
    title character varying(255),
    youtube_video_id character varying(255)
);


ALTER TABLE public.games OWNER TO postgres;

--
-- Name: games_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.games ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.games_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_favorite_games; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_favorite_games (
    user_id bigint NOT NULL,
    game_id bigint NOT NULL
);


ALTER TABLE public.user_favorite_games OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: games; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.games (id, cover_image_url, description, developer, genre, price, release_date, title, youtube_video_id) FROM stdin;
2	http://localhost:8080/game/god1.jpg	Kratos e Atreus affrontano il destino.	Santa Monica Studio	Action Adventure	69.99	2022-11-09	God of War Ragnarök	ixllGOX0Evw
3	http://localhost:8080/game/ho1.jpg	Un'avventura magica nel mondo di Harry Potter.	Avalanche Software	RPG	59.99	2023-02-10	Hogwarts Legacy	ecgrvh4kQRU
7	http://localhost:8080/game/re1.jpg	L’ottavo capitolo horror della saga Resident Evil con atmosfere inquietanti.	Capcom	Survival Horror	59.99	2021-05-07	Resident Evil Village	9BHPtci1OGo
1	http://localhost:8080/game/elden1.jpg	Un epico action RPG open world.	FromSoftware	Action RPG	59.99	2022-02-25	Elden Ring	JldMvQMO_5U
4	http://localhost:8080/game/wi1.jpg	Un GDR open world acclamato con una storia profonda e un mondo immenso.	CD Projekt Red	Action RPG	39.99	2015-05-19	The Witcher 3: Wild Hunt	xx8kQ4s5hCY
5	http://localhost:8080/game/ass1.jpg	Vivi l’epopea vichinga in questo capitolo open world di Assassin’s Creed.	Ubisoft	Action Adventure	59.99	2020-11-10	Assassin's Creed Valhalla	vCmS-HbtNfs
6	http://localhost:8080/game/de1.jpg	Un western epico con un mondo dettagliatissimo e una storia coinvolgente.	Rockstar Games	Action Adventure	49.99	2018-10-26	Red Dead Redemption 2	KuDR6e29eGI
\.


--
-- Data for Name: user_favorite_games; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_favorite_games (user_id, game_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, email, password_hash, username) FROM stdin;
\.


--
-- Name: games_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.games_id_seq', 7, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 24, true);


--
-- Name: games games_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: user_favorite_games user_favorite_games_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_favorite_games
    ADD CONSTRAINT user_favorite_games_pkey PRIMARY KEY (user_id, game_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: user_favorite_games fk1rdvefft4k44kxhfyywal9u1j; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_favorite_games
    ADD CONSTRAINT fk1rdvefft4k44kxhfyywal9u1j FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_favorite_games fktmrhr4juff6ic1ogos7dy7skt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_favorite_games
    ADD CONSTRAINT fktmrhr4juff6ic1ogos7dy7skt FOREIGN KEY (game_id) REFERENCES public.games(id);


--
-- PostgreSQL database dump complete
--

